#!/bin/bash 

PARAMS=(
 --files  /home/acald013/Spark/2.4/conf/log4j.properties   \
 --conf   spark.driver.extraJavaOptions=-Dlog4j.configuration=file:/home/acald013/Spark/2.4/conf/log4j.properties   \
 --jars   /home/acald013/.ivy2/cache/org.locationtech.jts/jts-core/bundles/jts-core-1.19.0.jar,/home/acald013/.ivy2/cache/org.jgrapht/jgrapht-core/jars/jgrapht-core-1.4.0.jar,/home/acald013/.ivy2/cache/org.apache.commons/commons-math3/jars/commons-math3-3.6.1.jar,/home/acald013/.ivy2/cache/org.apache.commons/commons-geometry-enclosing/jars/commons-geometry-enclosing-1.0-beta1.jar,/home/acald013/.ivy2/cache/org.apache.commons/commons-geometry-euclidean/jars/commons-geometry-euclidean-1.0-beta1.jar,/home/acald013/.ivy2/cache/org.rogach/scallop_2.11/jars/scallop_2.11-4.0.1.jar,/home/acald013/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.25.jar,/home/acald013/.ivy2/cache/org.spire-math/archery_2.11/jars/archery_2.11-0.6.0.jar  \
 --master yarn  \
 --class  edu.ucr.dblab.pflock.MF  
)

spark-submit ${PARAMS[@]} /home/acald013/Research/Scripts/Scala/PFlock/target/scala-2.11/pflock_2.11-0.1.0.jar $* 
