#!/bin/bash

## Pedestrian
echo "Pedestrians..."
python "$SUMO_HOME/tools/randomTrips.py" \
       --pedestrians \
       --net-file pasto.net.xml.gz --begin 0 --end 1000 --period 1 \
       --output-trip-file pasto.pedestrian.trips.xml --route-file pasto.pedestrian.rou.xml \
       --validate --remove-loops \
       --vehicle-class pedestrian --prefix ped \
       --min-distance 0 --max-distance 4000 \
       --random --seed 42 --duarouter-routing-threads 8 \
       --via-edge-types highway.motorway,highway.motorway_link,highway.trunk_link,highway.primary_link,highway.secondary_link,highway.tertiary_link 

## Bicycle...
echo "Bicycles..."
python "$SUMO_HOME/tools/randomTrips.py" \
       --net-file pasto.net.xml.gz --begin 0 --end 1000 --period 1 \
       --output-trip-file pasto.bicycle.trips.xml --route-file pasto.bicycle.rou.xml \
       --via-edge-types highway.motorway,highway.motorway_link,highway.trunk_link,highway.primary_link,highway.secondary_link,highway.tertiary_link \
       --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" \
       --validate --remove-loops \
       --vehicle-class bicycle --vclass bicycle --prefix bik \
       --min-distance 0 --max-distance 6000 \
       --random --seed 42 --duarouter-routing-threads 8

## Motorcycle
echo "Motorcycles..."
python "$SUMO_HOME/tools/randomTrips.py" \
       --net-file pasto.net.xml.gz --begin 0 --end 1000 --period 1 \
       --output-trip-file pasto.motorcycle.trips.xml --route-file pasto.motorcycle.rou.xml \
       --via-edge-types highway.motorway,highway.motorway_link,highway.trunk_link,highway.primary_link,highway.secondary_link,highway.tertiary_link \
       --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" \
       --validate --remove-loops \
       --vehicle-class motorcycle --vclass motorcycle --prefix mot \
       --min-distance 2000 --max-distance 8000 \
       --random --seed 42 --duarouter-routing-threads 8

## Car
echo "Cars..."
python "$SUMO_HOME/tools/randomTrips.py" \
       --net-file pasto.net.xml.gz --begin 0 --end 1000 --period 1 \
       --output-trip-file pasto.passenger.trips.xml --route-file pasto.passenger.rou.xml \
       --via-edge-types highway.motorway,highway.motorway_link,highway.trunk_link,highway.primary_link,highway.secondary_link,highway.tertiary_link \
       --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" \
       --validate --remove-loops \
       --vehicle-class passenger --vclass passenger --prefix car \
       --min-distance 3000 --max-distance 10000 \
       --allow-fringe.min-length 1000 --lanes \
       --random --seed 42 --duarouter-routing-threads 8

## Bus
echo "Buses..."
python "$SUMO_HOME/tools/randomTrips.py" \
       --net-file pasto.net.xml.gz --begin 0 --end 1000 --period 1 \
       --output-trip-file pasto.bus.trips.xml --route-file pasto.bus.rou.xml \
       --via-edge-types highway.motorway,highway.motorway_link,highway.trunk_link,highway.primary_link,highway.secondary_link,highway.tertiary_link \
       --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" \
       --validate --remove-loops \
       --vehicle-class bus --vclass bus --prefix bus \
       --min-distance 4000 --max-distance 10000 \
       --random --seed 42 --duarouter-routing-threads 8

## Truck
echo "Trucks..."
python "$SUMO_HOME/tools/randomTrips.py" \
       --net-file pasto.net.xml.gz --begin 0 --end 1000 --period 1 \
       --output-trip-file pasto.truck.trips.xml --route-file pasto.truck.rou.xml \
       --via-edge-types highway.motorway,highway.motorway_link,highway.trunk_link,highway.primary_link,highway.secondary_link,highway.tertiary_link \
       --trip-attributes "departLane=\"best\"" --fringe-start-attributes "departSpeed=\"max\"" \
       --validate --remove-loops \
       --vehicle-class truck --vclass truck --prefix tru \
       --min-distance 4000 --max-distance 10000 \
       --random --seed 42 --duarouter-routing-threads 8
