#!/bin/bash

JAR="$HOME/Research/Scripts/Scala/PFlocks/target/scala-2.11/pflocks_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="$LIBSPATH/geospark-1.3.1.jar:${LIBSPATH}/commons-numbers-fraction-1.0-beta1.jar:${LIBSPATH}/commons-numbers-core-1.0-beta1.jar"
CLASS="edu.ucr.dblab.pflock.test.Checker"

LOG_PATH=$1     # Path to the file with the list of point IDs to be checked...
SOURCE_PATH=$2  # Path to the file with the coordinates of the points...

scala -cp $LIBS:$JAR $CLASS $1 $2
