---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(plotly)

getStarts <- function(d){
  s = d %>% select(Stage, Nodes, Time, Tasks) %>% 
    group_by(Stage, Nodes) %>% 
    summarise(Start=min(Time), Tasks=min(Tasks)) %>% arrange(Start)
  return(s)
}
```

```{r}
RESEARCH_HOME = "/home/and/Documents/PhD/Research"
lines = readLines(paste0(RESEARCH_HOME, "/Scripts/Misc/tmp/monitor2.txt"))
lines = lines[grepl("|", lines)]
monitor = as_tibble(lines) %>%
  separate(value, into=c("Timestamp", "Time", "ID", "Nodes", "Cores", "Node", "Stage", "RDDs", "Tasks", "Times", "Load"), sep="\\|") %>%
  separate(ID, into=c(NA, NA, "ID"), sep="-") %>%
  select(ID, Time, Nodes, Stage, RDDs, Tasks, Load) %>%
  mutate(Time=as.numeric(Time), RDDs=as.numeric(RDDs), Tasks=as.numeric(Tasks), Load=as.numeric(Load)) %>%
  group_by(ID, Time, Nodes, Stage) %>% summarise(RDDs=mean(RDDs), Tasks=mean(Tasks), Load=mean(Load))
```

```{r}
d = monitor %>% filter(ID == "0051" || ID == "0052" || ID == "0053") %>% ungroup %>% 
  select(Time, Tasks, Nodes, Stage) %>% 
  mutate(Stage=factor(Stage), Nodes=factor(Nodes), Time=floor(Time*10.0)/10.0) %>% 
  group_by(Nodes, Stage, Time) %>%
  summarise(Tasks=mean(Tasks)) %>%
  arrange(Time, Tasks) 

head(d, n=30)
```

```{r}
p = ggplot(data = d, aes(x = Time, y = Tasks, group = 1)) +
  geom_line(aes(color = Nodes, linetype = Nodes)) +
  geom_point(data = getStarts(d), aes(x=Start, y=Tasks, group=Nodes, color=Nodes
                                      , text = paste(Stage,"<br>Start:",Start,"<br>",Tasks)))
```

```{r}
ggplotly(p, tooltip = c("text"))
```


