---
title: "LA_100K Dataset"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
Epsilon = 7
Mu = 5

```{r include=F}
library(tidyverse)
```

```{r echo=F}
fields = c("Timestamp", "Tag", "appId", "Cores", "Executors", "Epsilon", "Mu", "Partitions1", "Partitions", "Time", "Load")
data_path = "~/Documents/PhD/Research/Scripts/R/R02/nohup07.txt"
maximals = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% 
  filter(grepl("\\|MAXIMALS\\|", line)) %>%
  separate(line, into = fields, sep = "\\|") %>%
  mutate(Time = as.numeric(Time)) 
submit = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% 
  filter(grepl("spark-submit", line)) %>% separate(line, into=paste0("A", 1:14), sep = "--") %>%
  mutate(A3  = str_trim(A3))  %>% separate(A3 , into = c(NA,"Dataset"), sep = " ") %>% 
  mutate(A11 = str_trim(A11)) %>% separate(A11, into = c(NA,"MaxEntries"), sep = " ") %>% 
  mutate(MaxEntries = as.numeric(MaxEntries)) %>%
  separate(Dataset, into=c(NA,"Dataset"), sep = "/LA/") %>% separate(Dataset, into=c("Dataset", NA), sep = "\\.")

data = bind_cols(maximals, submit) %>% group_by(Dataset, MaxEntries, Partitions) %>% summarise(Time = mean(Time)) %>% 
  filter(MaxEntries <= 5000)
head(data, n = 24)

data$Dataset = factor(data$Dataset, levels = c("LA_50K", "LA_100K"))
p = ggplot(data = data, aes(x = factor(Dataset), y = Time, fill = factor(MaxEntries))) +
 geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
 theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0 )) +
 labs(x="Dataset", y="Time [s]", title="Execution time MF algorithm", fill="Max Entries") 
plot(p)
```

```{r echo=F}
fieldsMF = c("Timestamp", "Tag", "appId", "Executors", "Cores", "Status", "Duration", "Stage", "Time", "Load", "Interval")
data_path = "~/Documents/PhD/Research/Scripts/R/R02/nohup07.txt"
stages = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% filter(grepl("\\|MF\\|", line)) %>%
  filter(grepl("END", line)) %>% separate(line, into = fieldsMF, sep = "\\|") %>%
  filter(grepl("[E-F]\\.", Stage)) %>%
  mutate(Time = as.numeric(Time)) %>%
  select(Stage, Time) %>% mutate(id = rep(1:30, each = 2))

submit = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>%
  filter(grepl("spark-submit", line)) %>% separate(line, into=paste0("A", 1:14), sep = "--") %>%
  mutate(MaxEntries = str_trim(A11)) %>% separate(MaxEntries, c(NA,"MaxEntries"), sep = " ") %>%
  select(MaxEntries) %>% mutate(id = 1:30)

stage_names = tibble(StageId = c("A","B","C","D","E","F"), StageName = c("Partitioning points", "Finding pairs", "Computing centers", "Finding disks", "Partitioning disks", "Maximal disks"))
data = stages %>% inner_join(submit, by = "id") %>%
 group_by(MaxEntries, Stage) %>% summarise(Time = mean(Time)) %>%
 ungroup() %>% separate(Stage, c("StageId", NA), sep = "\\.") %>% inner_join(stage_names, by = "StageId") %>%
 mutate(Stage = paste0(StageId,".",StageName)) %>% select(MaxEntries, Stage, Time)
  head(data, n=30)

p = ggplot(data = data, aes(x = Stage, y = Time, fill = MaxEntries)) +
 geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
 theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0 )) +
 labs(x="Stage", y="Time [s]", title="Execution time break down by stage", fill="Max Entries") 
plot(p)
```
