
import org.rogach.scallop._

class FFConf(args: Seq[String]) extends ScallopConf(args) {
  val input:        ScallopOption[String]  =  opt[String]   (default = Some(""))
  val output:       ScallopOption[String]  =  opt[String]   (default = Some("/tmp/"))
  val tsfile:       ScallopOption[String]  =  opt[String]   (default = Some(""))
  val check_dir:    ScallopOption[String]  =  opt[String]   (default = Some("hdfs://dblab-rack15:9001/checkpoints"))
  val input_path:   ScallopOption[String]  =  opt[String]   (default = Some(""))
  val input_tag:    ScallopOption[String]  =  opt[String]   (default = Some(""))
  val p_grid:       ScallopOption[String]  =  opt[String]   (default  = Some(""))
  val m_grid:       ScallopOption[String]  =  opt[String]   (default  = Some(""))
  val offset:       ScallopOption[Int]     =  opt[Int]      (default  = Some(1))
  val distance:     ScallopOption[Double]  =  opt[Double]   (default  = Some(100.0))
  val epsilon:      ScallopOption[Double]  =  opt[Double]   (default  = Some(10.0))
  val mu:           ScallopOption[Int]     =  opt[Int]      (default  = Some(3))
  val delta:        ScallopOption[Int]     =  opt[Int]      (default  = Some(3))
  val master:       ScallopOption[String]  =  opt[String]   (default  = Some("169.235.27.138")) //spark://169.235.27.134:7077
  val host:         ScallopOption[String]  =  opt[String]   (default  = Some("169.235.27.138")) 
  val port:         ScallopOption[String]  =  opt[String]   (default  = Some("7077"))
  val portui:       ScallopOption[String]  =  opt[String]   (default  = Some("4040"))
  val sespg:        ScallopOption[String]  =  opt[String]   (default  = Some("epsg:2770"))
  val tespg:        ScallopOption[String]  =  opt[String]   (default  = Some("epsg:2770"))
  val spatial:      ScallopOption[String]  =  opt[String]   (default  = Some("KDBTREE"))
  val ffpartitions: ScallopOption[Int]     =  opt[Int]      (default  = Some(625))
  val mfpartitions: ScallopOption[Int]     =  opt[Int]      (default  = Some(4))
  val dpartitions:  ScallopOption[Int]     =  opt[Int]      (default  = Some(2))
  val dcustomx:     ScallopOption[Int]     =  opt[Int]      (default  = Some(30))
  val dcustomy:     ScallopOption[Int]     =  opt[Int]      (default  = Some(30))
  val ffcustomx:    ScallopOption[Double]  =  opt[Double]   (default  = Some(10.0))
  val ffcustomy:    ScallopOption[Double]  =  opt[Double]   (default  = Some(10.0))
  val mfcustomx:    ScallopOption[Double]  =  opt[Double]   (default  = Some(10.0))
  val mfcustomy:    ScallopOption[Double]  =  opt[Double]   (default  = Some(10.0))
  val cores:        ScallopOption[Int]     =  opt[Int]      (default  = Some(4))
  val executors:    ScallopOption[Int]     =  opt[Int]      (default  = Some(3))
  val tag:          ScallopOption[String]  =  opt[String]   (default  = Some(""))
  val timestamp:    ScallopOption[Int]     =  opt[Int]      (default  = Some(-1))
  val mininterval:  ScallopOption[Int]     =  opt[Int]      (default  = Some(0))
  val maxinterval:  ScallopOption[Int]     =  opt[Int]      (default  = Some(20))
  val fftimestamp:  ScallopOption[Int]     =  opt[Int]      (default  = Some(10))

  val levels:       ScallopOption[Int]      = opt[Int]     (default  = Some(8))
  val entries:      ScallopOption[Int]      = opt[Int]     (default  = Some(200))
  val frame:        ScallopOption[Double]   = opt[Double]  (default  = Some(1.0))
  val fraction:     ScallopOption[Double]   = opt[Double]  (default  = Some(0.1))
  val fraction2:    ScallopOption[Double]   = opt[Double]  (default  = Some(0.1))
  
  val ffdebug:      ScallopOption[Boolean] =  opt[Boolean]  (default  = Some(false))
  val mfdebug:      ScallopOption[Boolean] =  opt[Boolean]  (default  = Some(false))
  val info:         ScallopOption[Boolean] =  opt[Boolean]  (default  = Some(false))
  val local:        ScallopOption[Boolean] =  opt[Boolean]  (default  = Some(false))
  val stream:       ScallopOption[Boolean] =  opt[Boolean]  (default  = Some(false))
  val save:         ScallopOption[Boolean] =  opt[Boolean]  (default  = Some(false))
  val mfgrid:       ScallopOption[Boolean] =  opt[Boolean]  (default  = Some(false))

  val sep:      ScallopOption[String] = opt[String] (default = Some("_"))
  val ext:      ScallopOption[String] = opt[String] (default = Some("tsv"))
  val rate:     ScallopOption[Long]   = opt[Long]   (default = Some(1000L))
  val n:        ScallopOption[Int]    = opt[Int]    (default = Some(5))
  val i:        ScallopOption[Int]    = opt[Int]    (default = Some(0))
  val interval: ScallopOption[Int]    = opt[Int]    (default = Some(1))
  val debug:    ScallopOption[Boolean]= opt[Boolean](default = Some(false))
  val width:    ScallopOption[Double] = opt[Double]    (default = Some(500.0))
  val envelope: ScallopOption[Boolean]= opt[Boolean]   (default = Some(false))
  val xmin:     ScallopOption[Double] = opt[Double]    (default = Some(0.0))
  val ymin:     ScallopOption[Double] = opt[Double]    (default = Some(0.0))
  val xmax:     ScallopOption[Double] = opt[Double]    (default = Some(3.0))
  val ymax:     ScallopOption[Double] = opt[Double]    (default = Some(3.0))
  val speed:    ScallopOption[Double] = opt[Double]    (default = Some(10.0))
  verify()
}

