---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(plotly)
source("/home/and/Documents/PhD/Research/Scripts/R/R13/tasksMetrics.R")

nohup = "/home/and/Documents/PhD/Research/Scripts/Misc/tmp/nohup.tsv"
appsE1_1 = getCustomStages(nohup, 282)
appsE1_2 = getCustomStages(nohup, 284)
appsE1_3 = getCustomStages(nohup, 286)
appsE1_4 = getCustomStages(nohup, 288)
appsE1_5 = getCustomStages(nohup, 290)
stagesE1 = rbind(appsE1_1,appsE1_2,appsE1_3, appsE1_4, appsE1_5)
appsE3_1 = getCustomStages(nohup, 281)
appsE3_2 = getCustomStages(nohup, 283)
appsE3_3 = getCustomStages(nohup, 285)
appsE3_4 = getCustomStages(nohup, 287)
appsE3_5 = getCustomStages(nohup, 289)
stagesE3 = rbind(appsE3_1,appsE3_2,appsE3_3, appsE3_4, appsE3_5)

stages = rbind(stagesE1, stagesE3) %>% select(Interval, Stage, Executors, Duration) %>%
  mutate(Stage = paste(str_pad(Interval,2,"left"), Stage)) %>%
  select(Stage, Executors, Duration) %>%
  group_by(Stage, Executors) %>% summarise(Duration = mean(Duration))

head(stages)
```

```{r}
p = ggplot(data = stages, aes(x = Stage, y = Duration, fill = Executors)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stages", y="Duration(s)")
ggplotly(p)
```