#!/bin/bash

JAR="$HOME/Research/Scripts/Scala/FlockFinderByCliques/target/scala-2.11/flockfinderbycliques_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="${LIBSPATH}/jgrapht-core-1.4.0.jar:${LIBSPATH}/JTSplus-0.1.4.jar:${LIBSPATH}/commons-math3-3.6.1.jar"
CLASS="edu.ucr.dblab.FlockFinder"

scala -cp $LIBS:$JAR $CLASS $1 $2 $3
