#!/bin/bash

JAR="$HOME/Research/Scripts/Scala/FlockFinderByCliques/target/scala-2.11/flockfinderbycliques_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="${LIBSPATH}/geospark-1.2.0.jar:${LIBSPATH}/commons-numbers-fraction-1.0-beta1.jar:${LIBSPATH}/commons-numbers-core-1.0-beta1.jar"
CLASS="edu.ucr.dblab.pflock.welzl.Welzl"

scala -cp $LIBS:$JAR $CLASS
