#!/bin/bash

DATASET=$1
N=$2

ES=( 1 ) # epsilon
SC=( 20 ) # step

for n in $(seq 1 "$N")
do
	for s in "${SC[@]}"
	do
		for e in "${ES[@]}"
		do
			echo ""
			echo "Running ./pflocks_spark_desktop --master local[20] --input "$DATASET" --epsilon "$e" --step "$s" --output /home/and/tmp/  --scapacity 200 --partitioner Fixed -e"
			echo ""
			./pflocks_spark_desktop --master local[20] --input "$DATASET" --epsilon "$e" --step "$s" --output /home/and/tmp/  --scapacity 200 --partitioner Fixed -e
		done
	done
done
