---
fontsize: 9pt
geometry: margin=2cm
classoption: landscape
output: 
  pdf_document:
    keep_tex: yes
---

```{r setup, include=FALSE}
library(tidyverse)
library(xtable)
library(sf)
```

```{r histogram, echo=FALSE, include=FALSE}
files <- as_tibble(list.files(path="data/")) |> 
  separate(col = value, into = c("filename", NA), sep = "\\.", remove = F) |>
  separate(col = filename, into = c("tag", "time", "capacity", "ncells", "epsilon"), sep = "_") |>
  mutate(time = as.numeric(str_sub(time, 2, -1)), 
         capacity = as.numeric(str_sub(capacity, 2, -1)),
         ncells = as.numeric(str_sub(ncells, 2, -1)),
         epsilon = as.numeric(str_sub(epsilon, 2, -1)) 
         ) |>
  select(value, time, epsilon, capacity) |> 
  #filter(time == 318) |> 
  arrange(time, epsilon, capacity) 

out = NULL
for(afile in files$value){
#for(afile in files$value[1:3]){
  arr = str_split(afile, "_")
  time_instant = str_sub(arr[[1]][2],2,-1)
  capacity     = str_sub(arr[[1]][3],2,-1)
  leafs        = str_sub(arr[[1]][4],2,-1)
  epsilon      = str_split(str_sub(arr[[1]][5],2,-1), "\\.")[[1]][1]  
  out = c(out,  knitr::knit_expand('distance_child.Rmd', quiet = TRUE))
}
```

`r paste(knitr::knit(text = out), collapse = '\n')`
