```{r, echo=FALSE, include=FALSE, message=FALSE}
  data = read_tsv("data/{{afile}}", col_names = c("wkt", "cid", "n", "d"))
```

```{r,echo=FALSE, results='asis'} 
cat(paste0("\nTime instant : {{time_instant}} (capacity={{capacity}}, leafs={{leafs}}, epsilon={{epsilon}})."))
```
------------------------------------

```{r, echo=FALSE, include=FALSE, fig.width=7}
CRS = 6423
geom = st_as_sf(data, crs = CRS, wkt = 1)
filename = paste0("time_instants/LA_50K_T{{time_instant}}.tsv")
points = read_tsv(filename, col_names = c("oid", "x", "y", "tid")) 

stats = unclass(summary(data$n))
t1 = xtable(t(as.data.frame(stats)))

stats = unclass(summary(data$d))
t2 = xtable(t(as.data.frame(stats)))

```

```{r,echo=FALSE, results='asis'}
cat("\\begin{minipage}{0.5\\textwidth} \n")
  cat("\\centering \n")
  print(t1, comment=FALSE, floating=FALSE)
  cat("\\vspace{0.5cm} \n")
```

```{r p1_{{time_instant}}_{{capacity}}_{{epsilon}}, echo=FALSE, message=FALSE, out.width="100%", out.height="80%"}
  p1 = ggplot(geom) + 
  geom_sf(aes(fill = n)) + 
  coord_sf(datum = NA) +
  geom_point(data = points, aes(x = x, y = y), size = 0.1, alpha = 0.1) +   
  scale_fill_gradient(low = "#FFFFFF", high ="#FF0000", name = "Points per cell") +
  xlab("") + ylab("") +
  theme_minimal() +
  theme(axis.text = element_blank(), 
        legend.position="top",
        legend.key.height = unit(0.25, 'cm'),
        legend.key.width  = unit(0.75, 'cm'),
        legend.title      = element_text(size=5),
        legend.text       = element_text(size=5),
        legend.margin     = margin(10, 0, 0, 0),
        legend.box.margin = margin(0, 0, -20, 0)
        )
  print(p1)
```

```{r,echo=FALSE, results='asis'}
cat("\\end{minipage} \n")
cat("\\begin{minipage}{0.5\\textwidth} \n")
  cat("\\centering \n")
  print(t2, comment=FALSE, floating=FALSE)
  cat("\\vspace{0.5cm} \n")
```

```{r p2_{{time_instant}}_{{capacity}}_{{epsilon}}, echo=FALSE, message=FALSE, out.width="100%", out.height="80%"}
  p2 = ggplot(geom) + 
  geom_sf(aes(fill = d)) + 
  coord_sf(datum = NA) +
  geom_point(data = points, aes(x = x, y = y), size = 0.1, alpha = 0.1) +   
  scale_fill_gradient(low = "#FFFFFF", high ="#FF0000", name = "Pairs per cell") +
  xlab("") + ylab("") +
  theme_minimal() +
  theme(axis.text = element_blank(), 
        legend.position="top",
        legend.key.height = unit(0.25, 'cm'),
        legend.key.width  = unit(0.75, 'cm'),
        legend.title      = element_text(size=5),
        legend.text       = element_text(size=5),
        legend.margin     = margin(10, 0, 0, 0),
        legend.box.margin = margin(0, 0, -20, 0)
        )
  print(p2)
```

```{r,echo=FALSE, results='asis'}
cat("\\end{minipage} \n")
```

\pagebreak