% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
  9pt,
  landscape]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=2cm]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\author{}
\date{\vspace{-2.5em}}

\begin{document}

\hypertarget{time-instant-320-capacity100-leafs1366-epsilon12.}{%
\subsection{Time instant : 320 (capacity=100, leafs=1366,
epsilon=12).}\label{time-instant-320-capacity100-leafs1366-epsilon12.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 1.00 & 18.00 & 35.00 & 41.86 & 60.00 & 245.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_100_12-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 1.00 & 3.00 & 45.05 & 13.00 & 3494.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_100_12-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity200-leafs613-epsilon12.}{%
\subsection{Time instant : 320 (capacity=200, leafs=613,
epsilon=12).}\label{time-instant-320-capacity200-leafs613-epsilon12.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 1.00 & 42.50 & 79.00 & 88.38 & 126.00 & 301.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_200_12-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 3.00 & 10.00 & 81.64 & 29.00 & 3645.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_200_12-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity400-leafs316-epsilon12.}{%
\subsection{Time instant : 320 (capacity=400, leafs=316,
epsilon=12).}\label{time-instant-320-capacity400-leafs316-epsilon12.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 103.75 & 156.00 & 167.48 & 223.00 & 541.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_400_12-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 6.75 & 24.00 & 149.97 & 62.00 & 5310.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_400_12-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity600-leafs208-epsilon12.}{%
\subsection{Time instant : 320 (capacity=600, leafs=208,
epsilon=12).}\label{time-instant-320-capacity600-leafs208-epsilon12.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 144.00 & 218.00 & 251.43 & 339.25 & 610.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_600_12-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 13.00 & 41.00 & 206.40 & 86.50 & 7755.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_600_12-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity800-leafs157-epsilon12.}{%
\subsection{Time instant : 320 (capacity=800, leafs=157,
epsilon=12).}\label{time-instant-320-capacity800-leafs157-epsilon12.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 186.00 & 295.00 & 331.68 & 464.00 & 796.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_800_12-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 25.00 & 52.00 & 272.80 & 118.00 & 7755.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_800_12-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity1000-leafs127-epsilon12.}{%
\subsection{Time instant : 320 (capacity=1000, leafs=127,
epsilon=12).}\label{time-instant-320-capacity1000-leafs127-epsilon12.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 208.50 & 372.00 & 408.91 & 558.50 & 1006.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_1000_12-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 29.50 & 64.00 & 337.06 & 173.00 & 7755.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_1000_12-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity100-leafs1366-epsilon14.}{%
\subsection{Time instant : 320 (capacity=100, leafs=1366,
epsilon=14).}\label{time-instant-320-capacity100-leafs1366-epsilon14.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 1.00 & 18.00 & 35.00 & 42.60 & 62.00 & 282.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_100_14-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 1.00 & 4.00 & 59.00 & 16.00 & 4795.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_100_14-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity200-leafs613-epsilon14.}{%
\subsection{Time instant : 320 (capacity=200, leafs=613,
epsilon=14).}\label{time-instant-320-capacity200-leafs613-epsilon14.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 1.00 & 43.00 & 79.00 & 89.42 & 127.50 & 322.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_200_14-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 4.00 & 12.00 & 104.88 & 34.00 & 4795.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_200_14-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity400-leafs316-epsilon14.}{%
\subsection{Time instant : 320 (capacity=400, leafs=316,
epsilon=14).}\label{time-instant-320-capacity400-leafs316-epsilon14.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 103.75 & 156.00 & 168.81 & 227.25 & 564.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_400_14-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 8.00 & 28.50 & 190.20 & 74.25 & 6858.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_400_14-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity600-leafs208-epsilon14.}{%
\subsection{Time instant : 320 (capacity=600, leafs=208,
epsilon=14).}\label{time-instant-320-capacity600-leafs208-epsilon14.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 144.25 & 218.50 & 253.01 & 341.50 & 639.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_600_14-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 15.00 & 49.50 & 258.82 & 106.00 & 9662.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_600_14-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity800-leafs157-epsilon14.}{%
\subsection{Time instant : 320 (capacity=800, leafs=157,
epsilon=14).}\label{time-instant-320-capacity800-leafs157-epsilon14.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 186.00 & 295.00 & 333.55 & 465.00 & 798.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_800_14-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 29.00 & 65.00 & 342.11 & 138.00 & 9662.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_800_14-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity1000-leafs127-epsilon14.}{%
\subsection{Time instant : 320 (capacity=1000, leafs=127,
epsilon=14).}\label{time-instant-320-capacity1000-leafs127-epsilon14.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 208.50 & 372.00 & 411.09 & 564.50 & 1008.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_1000_14-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 35.00 & 78.00 & 422.68 & 209.00 & 9662.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_1000_14-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity100-leafs1366-epsilon16.}{%
\subsection{Time instant : 320 (capacity=100, leafs=1366,
epsilon=16).}\label{time-instant-320-capacity100-leafs1366-epsilon16.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 1.00 & 18.00 & 36.00 & 43.45 & 62.00 & 311.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_100_16-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 1.00 & 5.00 & 75.20 & 20.00 & 6291.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_100_16-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity200-leafs613-epsilon16.}{%
\subsection{Time instant : 320 (capacity=200, leafs=613,
epsilon=16).}\label{time-instant-320-capacity200-leafs613-epsilon16.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 1.00 & 43.50 & 80.00 & 90.50 & 129.00 & 330.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_200_16-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 5.00 & 14.00 & 130.61 & 42.00 & 6291.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_200_16-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity400-leafs316-epsilon16.}{%
\subsection{Time instant : 320 (capacity=400, leafs=316,
epsilon=16).}\label{time-instant-320-capacity400-leafs316-epsilon16.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 105.25 & 156.50 & 170.19 & 227.25 & 592.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_400_16-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 9.00 & 33.00 & 233.89 & 88.25 & 8706.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_400_16-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity600-leafs208-epsilon16.}{%
\subsection{Time instant : 320 (capacity=600, leafs=208,
epsilon=16).}\label{time-instant-320-capacity600-leafs208-epsilon16.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 148.00 & 220.50 & 254.55 & 343.00 & 672.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_600_16-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 19.75 & 58.00 & 315.82 & 123.25 & 11884.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_600_16-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity800-leafs157-epsilon16.}{%
\subsection{Time instant : 320 (capacity=800, leafs=157,
epsilon=16).}\label{time-instant-320-capacity800-leafs157-epsilon16.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 186.00 & 295.00 & 335.32 & 480.00 & 800.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_800_16-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 36.00 & 78.00 & 417.36 & 168.00 & 11884.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_800_16-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity1000-leafs127-epsilon16.}{%
\subsection{Time instant : 320 (capacity=1000, leafs=127,
epsilon=16).}\label{time-instant-320-capacity1000-leafs127-epsilon16.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 209.00 & 376.00 & 413.10 & 569.00 & 1012.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_1000_16-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 41.00 & 96.00 & 515.57 & 254.00 & 11884.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_1000_16-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity100-leafs1366-epsilon18.}{%
\subsection{Time instant : 320 (capacity=100, leafs=1366,
epsilon=18).}\label{time-instant-320-capacity100-leafs1366-epsilon18.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 1.00 & 19.00 & 36.00 & 44.32 & 63.00 & 344.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_100_18-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 1.00 & 6.00 & 95.20 & 23.00 & 8083.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_100_18-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity200-leafs613-epsilon18.}{%
\subsection{Time instant : 320 (capacity=200, leafs=613,
epsilon=18).}\label{time-instant-320-capacity200-leafs613-epsilon18.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 2.00 & 44.00 & 81.00 & 91.58 & 129.50 & 357.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_200_18-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 6.00 & 17.00 & 161.28 & 49.00 & 8083.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_200_18-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity400-leafs316-epsilon18.}{%
\subsection{Time instant : 320 (capacity=400, leafs=316,
epsilon=18).}\label{time-instant-320-capacity400-leafs316-epsilon18.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 105.25 & 158.00 & 171.62 & 228.25 & 616.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_400_18-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 10.00 & 39.00 & 286.91 & 101.50 & 10929.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_400_18-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity600-leafs208-epsilon18.}{%
\subsection{Time instant : 320 (capacity=600, leafs=208,
epsilon=18).}\label{time-instant-320-capacity600-leafs208-epsilon18.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 150.50 & 222.00 & 256.26 & 347.00 & 709.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_600_18-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 24.00 & 69.50 & 384.49 & 147.25 & 14863.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_600_18-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity800-leafs157-epsilon18.}{%
\subsection{Time instant : 320 (capacity=800, leafs=157,
epsilon=18).}\label{time-instant-320-capacity800-leafs157-epsilon18.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 186.00 & 295.00 & 337.42 & 482.00 & 809.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_800_18-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 40.00 & 92.00 & 508.12 & 199.00 & 14863.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_800_18-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity1000-leafs127-epsilon18.}{%
\subsection{Time instant : 320 (capacity=1000, leafs=127,
epsilon=18).}\label{time-instant-320-capacity1000-leafs127-epsilon18.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 209.50 & 377.00 & 415.52 & 569.00 & 1014.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_1000_18-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 47.00 & 112.00 & 627.66 & 293.00 & 14863.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_1000_18-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity100-leafs1366-epsilon20.}{%
\subsection{Time instant : 320 (capacity=100, leafs=1366,
epsilon=20).}\label{time-instant-320-capacity100-leafs1366-epsilon20.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 1.00 & 19.00 & 37.00 & 45.32 & 64.00 & 378.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_100_20-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 2.00 & 7.00 & 118.53 & 28.00 & 10161.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_100_20-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity200-leafs613-epsilon20.}{%
\subsection{Time instant : 320 (capacity=200, leafs=613,
epsilon=20).}\label{time-instant-320-capacity200-leafs613-epsilon20.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 2.00 & 44.00 & 82.00 & 92.84 & 130.50 & 384.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_200_20-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 6.00 & 19.00 & 196.56 & 56.00 & 10161.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_200_20-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity400-leafs316-epsilon20.}{%
\subsection{Time instant : 320 (capacity=400, leafs=316,
epsilon=20).}\label{time-instant-320-capacity400-leafs316-epsilon20.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 105.25 & 160.00 & 173.25 & 229.25 & 639.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_400_20-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 12.00 & 45.00 & 346.30 & 120.25 & 13123.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_400_20-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity600-leafs208-epsilon20.}{%
\subsection{Time instant : 320 (capacity=600, leafs=208,
epsilon=20).}\label{time-instant-320-capacity600-leafs208-epsilon20.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 150.75 & 223.00 & 258.21 & 348.00 & 754.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_600_20-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 27.00 & 81.50 & 459.84 & 163.75 & 18061.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_600_20-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity800-leafs157-epsilon20.}{%
\subsection{Time instant : 320 (capacity=800, leafs=157,
epsilon=20).}\label{time-instant-320-capacity800-leafs157-epsilon20.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 186.00 & 304.00 & 339.80 & 490.00 & 815.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_800_20-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 47.00 & 103.00 & 607.63 & 233.00 & 18061.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_800_20-1} 

\end{minipage}

\pagebreak

\hypertarget{time-instant-320-capacity1000-leafs127-epsilon20.}{%
\subsection{Time instant : 320 (capacity=1000, leafs=127,
epsilon=20).}\label{time-instant-320-capacity1000-leafs127-epsilon20.}}

\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 3.00 & 210.00 & 384.00 & 418.20 & 573.00 & 1016.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p1_320_1000_20-1} 

\end{minipage} 
\begin{minipage}{0.5\textwidth} 
\centering 
\begin{tabular}{rrrrrrr}
  \hline
 & Min. & 1st Qu. & Median & Mean & 3rd Qu. & Max. \\ 
  \hline
stats & 0.00 & 54.00 & 129.00 & 750.52 & 335.00 & 18061.00 \\ 
   \hline
\end{tabular}
\vspace{0.5cm} 


\includegraphics[width=1\linewidth,height=0.8\textheight]{distance_files/figure-latex/p2_320_1000_20-1} 

\end{minipage}

\pagebreak

\end{document}
