---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
```


```{r}
fields = c("Timestamp", "Tag", "appId", "Cores", "Executors", "Epsilon", "Mu", "Delta", "Time", "Load")
data_path = "~/Documents/PhD/Research/Scripts/R/R15/nohupDelta.txt"
data = enframe(read_lines(data_path), name="n", value="line") %>% select(line) %>% 
  filter(grepl("PFLOCK", line)) %>% separate(line, into = fields, sep = "\\|") %>%
  mutate(Time = as.numeric(Time), Executors = as.numeric(Executors)) %>%
  filter(Executors == 15) %>%
  group_by(Delta) %>% summarise(Time = mean(Time)) 

head(data)
```

```{r}
p = ggplot(data = data, aes(x = Delta, y = Time)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 0, hjust = 1)) +
  labs(x="Delta (number of time intervals)", y="Time in seconds", title="Execution time after variying Delta parameter") 
plot(p)
```

* Dataset: Berlin (x3), Executors: 15 (4 cores each), Epsilon: 100m, Mu: 3.
