#!/bin/bash

DATASET=$1
EPSILON=$2
MU=$3
DELTA=$4

~/opt/BFE_Modified/build/flocks -m BFE \
	-d $EPSILON \
	-s $MU \
	-l $DELTA \
	-f $DATASET > /tmp/bfe.log

FILENAME="BFE_E${EPSILON}_M${MU}_D${DELTA}.txt"
cat /tmp/bfe.log | grep -P "\d\, \d+\," > /tmp/$FILENAME

cat /tmp/$FILENAME

grep "Closing stream" /tmp/bfe.log

