#!/bin/bash

MFSTART=32
MFSTEP=2
MFEND=38

FFSTART=42
FFSTEP=2
FFEND=64

for MF in `seq $MFSTART $MFSTEP $MFEND`; do
    for FF in `seq $FFSTART $FFSTEP $FFEND`; do
	echo "spark-submit --class FF /home/acald013/Research/GeoSpark/target/scala-2.11/pflock_2.11-0.1.0.jar --input /home/acald013/Research/Datasets/Berlin/SideBySide/B1.tsv --epsilon 110 --mu 3 --delta 3 --distance 100 --cores 4 --executors 1 --spatial CUSTOM --customx $FF --customy $FF --customxmf $MF --customymf $MF --fftimestamp 3 --ffdebug"
	spark-submit --class FF /home/acald013/Research/GeoSpark/target/scala-2.11/pflock_2.11-0.1.0.jar --input /home/acald013/Research/Datasets/Berlin/SideBySide/B1.tsv --epsilon 110 --mu 3 --delta 3 --distance 100 --cores 4 --executors 1 --spatial CUSTOM --customx $FF --customy $FF --customxmf $MF --customymf $MF --fftimestamp 3 --ffdebug
    done
done
