#!/bin/bash

DATASET=$1
N=$2

ES=( 5 10 ) # epsilon

for n in $(seq 1 "$N")
do
	for e in "${ES[@]}"
	do
		echo ""
		echo "Running ./pflocks_spark --input $DATASET --epsilon $e (iteration $n)"
		echo ""
		./pflocks_spark --input "$DATASET" --epsilon "$e" 
	done
done