#!/bin/bash

INPUT=~/Research/Datasets/dense2.tsv
EPSILON=1
SIZE=100
DEBUG=""

while [ "$1" != "" ]; do
    case $1 in
        -i|--input) shift
		    INPUT="$1"
		    ;;
        -e|--epsilon) shift
		      EPSILON="$1"
		      ;;
        -s|--size) shift
		      SIZE="$1"
		      ;;
        -d|--debug) DEBUG="--debug"
		    ;;
	-*|--*) echo "Unknown option $1"
		exit 1
		;;
    esac
    shift
done

echo "INPUT   = $INPUT"
echo "EPSILON = $EPSILON"
echo "SIZE    = $SIZE"
if [ "$DEBUG" != "" ]; then
echo "DEBUG   = YES"
fi

JARS_PATH=$HOME/Spark/2.4/jars

JARS=${JARS_PATH}/jts-core-1.19.0.jar
JARS=${JARS}:${JARS_PATH}/scallop_2.11-4.0.1.jar
JARS=${JARS}:${JARS_PATH}/slf4j-api-1.7.25.jar
JARS=${JARS}:${JARS_PATH}/slf4j-simple-1.7.25.jar

LOG_FILE=$HOME/Spark/2.4/conf/simplelogger.properties
CLASS=edu.ucr.dblab.sitester.SITester
JAR=$HOME/Research/Scripts/Scala/SITester/target/scala-2.11/sitester_2.11-0.1.jar

PARAMS=(
    -cp $JARS:$JAR:$LOG_FILE \
	-Dorg.slf4j.simpleLogger.showDateTime=true \
	-Dorg.slf4j.simpleLogger.dateTimeFormat="yyyy-MM-dd'T'HH:mm:ss.SSS" \
	-Dorg.slf4j.simpleLogger.showThreadName=false \
	-Dorg.slf4j.simpleLogger.showLogName=false \
	$CLASS \
	--input $INPUT --epsilon $EPSILON --size $SIZE $DEBUG
)

echo "scala ${PARAMS[@]}"
scala ${PARAMS[@]}
