#!/bin/bash

INPUT=$1
EPSILON=$2
SIZE=$3

JARS_PATH=$HOME/Spark/2.4/jars

JARS=${JARS_PATH}/jts-core-1.19.0.jar
JARS=${JARS},${JARS_PATH}/scallop_2.11-4.0.1.jar
JARS=${JARS},${JARS_PATH}/slf4j-api-1.7.25.jar

MASTER=local[1]

LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties
CLASS=edu.ucr.dblab.sitester.SITester
JAR=$HOME/Research/Scripts/Scala/SITester/target/scala-2.11/sitester_2.11-0.1.jar

PARAMS=(
    --files $LOG_FILE \
    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
    --jars $JARS \
    --master $MASTER --deploy-mode client \
    --class $CLASS $JAR
    --input $INPUT --epsilon $EPSILON --size $SIZE 
)

echo "spark-submit ${PARAMS[@]}"
spark-submit ${PARAMS[@]}
