---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(plotly)

getStarts <- function(d){
  s = d %>% select(Stage, Nodes, Time, y) %>% 
    group_by(Stage, Nodes) %>% 
    summarise(Start=min(Time), y=min(y)) %>% arrange(Start)
  return(s)
}
```

```{r}
RESEARCH_HOME = "/home/and/Documents/PhD/Research"
lines = readLines(paste0(RESEARCH_HOME, "/Scripts/R/Benchmarks/MultiAndSingleNode/R12/aws/monitor.txt"))
lines = lines[grepl("\\|SCALE\\|", lines)]
monitor = as_tibble(lines) %>%
  separate(value, into=c("Timestamp", "Scale", "Time", "ID", "Nodes", "Stage", "RDDs", "Task", "Dura", "Load"), sep="\\|") %>%
  separate(ID, into=c(NA, NA, "ID"), sep="_") %>%
  select(ID, Time, Nodes, Stage, RDDs, Task, Load) %>%
  mutate(Time=as.numeric(Time), RDDs=as.numeric(RDDs), Tasks=as.numeric(Task), Load=as.numeric(Load)) %>%
  group_by(ID, Time, Nodes, Stage) %>% summarise(RDDs=mean(RDDs), Tasks=mean(Tasks), Load=mean(Load))
head(monitor)
```

```{r}
d = monitor %>% filter(ID %in% c("0028","0029","0030")) %>% ungroup %>% 
  mutate(y = Load) %>%
  select(Time, y, Nodes, Stage) %>% 
  arrange(Time) 
starts = getStarts(d)
```

```{r}
starts$Label = ""
starts[starts$Stage == "count at MF.scala:194", "Label"] = "<br>Maximal disk find start"
starts[starts$Stage == "rdd at MF.scala:223", "Label"] = "<br>Maximal disk find end"

p = ggplot(data = d, aes(x = Time, y = y, group = 1, color = Nodes, linetype = Nodes)) +
  geom_line() +
  geom_point(data = starts, aes(x=Start, y=y, group=1, color=Nodes, text = paste0(Stage,"<br>Start: ",Start,", Load: ",y,"<br>",Label))) +
  labs(x="Time(s)", y="Load (Mb)")
```

```{r}
ggplotly(p, tooltip = c("text"))
```


