---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(lubridate)
library(plotly)

RESEARCH_HOME = "/home/and/Documents/PhD/Research"
PATH_FILES = "/Scripts/R/Benchmarks/MultiAndSingleNode/R12/dblab/"
NOHUP_FILE = "nohup10.tsv"
lines = readLines(paste0(RESEARCH_HOME, PATH_FILES, NOHUP_FILE))
lines = lines[grepl("\\|STAGES\\|", lines)]
stages0 = as_tibble(lines) %>%
  separate(value, into=c("Timestamp", "Title", "Nodes", "Cores","StageID", "Stage", "Start", "End", "nTasks", "Runtime", "CPUTime", "InputBytes", "InputRecords", "ShuffleBytes", "ShuffleRecords", "ID"), sep="\\|") %>%
  separate(ID, into=c(NA, NA, "ID"), sep="-") %>%
  mutate(ID = as.numeric(ID), Stage = str_trim(Stage)) %>%
  mutate(uStart = parse_datetime(str_replace(str_trim(Start), "GMT", "")), 
         uEnd = parse_datetime(str_replace(str_trim(End), "GMT", ""))) %>%
  mutate(Duration = as.numeric(uEnd - uStart), 
         uStart = uStart - hours(7),
         Stage = paste0(str_pad(str_trim(StageID), pad="0", side="left", width=5),"_",Stage)) %>%
  select(uStart, Nodes, Stage, Duration) %>%
  arrange(uStart)
stages0$Interval = -2
stages0$FFStage = ""
stages0$Status = ""
head(stages0, n=15)
```

```{r}
lines = readLines(paste0(RESEARCH_HOME, PATH_FILES, NOHUP_FILE))
lines = lines[grepl("\\|[1-6]\\.", lines)]
ff = as_tibble(lines) %>%
  separate(value, into=c("Timestamp", "Title", "ID", "Nodes", "Cores", "Status", "Time", "Stage", "Duration", "Load", "Interval"), sep="\\|") %>%
  separate(ID, into=c(NA, NA, "ID"), sep="-") %>%
  mutate(ID = as.numeric(ID), Stage = str_trim(Stage), Duration = as.numeric(Duration)) %>%
  mutate(uStart = parse_datetime(str_replace(Timestamp, ",", ".")), FFStage = Stage, Status = str_trim(Status)) %>%
  select(uStart, Nodes, Stage, Duration, Interval, FFStage, Status)

head(ff)
```

```{r}
stages = rbind(stages0, ff) %>% arrange(uStart)

head(stages, n=100)
```

```{r}
n = nrow(stages)
ffstage  = ""
interval = ""
for(row in 1:n){
  if(stages[row, "Status"] == "START"){
    ffstage  = stages[row, "FFStage"]
    interval = stages[row, "Interval"]
  } else {
    if(stages[row, "Status"] == "END"){
      ffstage  = ""
      interval = ""
    } else {
      stages[row, "FFStage"] = ffstage
      stages[row, "Interval"] = interval
    }
  }
}

head(stages, n=100)
```

```{r}
s = stages %>% filter(Interval != "") %>% filter(grepl("_", Stage)) %>% 
  mutate(FFStage = paste0(Interval,".",FFStage)) %>% 
  select(Nodes, Stage, Duration, FFStage, Interval)

head(s)
```

```{r}
p = ggplot(data = s %>% filter(Interval == 1), aes(x = Stage, y = Duration, fill = Nodes)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stages", y="Duration(s)")
ggplotly(p)
```


```{r}
p = ggplot(data = s %>% filter(Interval == 2), aes(x = Stage, y = Duration, fill = Nodes)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stages", y="Duration(s)")
ggplotly(p)
```
