#!/bin/bash

## Pedestrian
echo "Pedestrians..."
python "$SUMO_HOME/tools/randomTrips.py" \
       --pedestrians \
       --net-file pasto.net.xml.gz --begin 0 --end 1000 --period 1 \
       --output-trip-file pasto.pedestrian.trips.xml --route-file pasto.pedestrian.rou.xml \
       --validate --remove-loops \
       --vehicle-class pedestrian --prefix ped \
       --min-distance 0 --max-distance 4000 \
       --random --seed 42 --duarouter-routing-threads 8 \
       --via-edge-types highway.motorway,highway.motorway_link,highway.trunk_link,highway.primary_link,highway.secondary_link,highway.tertiary_link 
