---
title: "LA_5K"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r include=F}
library(tidyverse)
```

```{r echo=F}
fields = c("Timestamp", "Tag", "appId", "Cores", "Executors", "Epsilon", "Mu", "Partitions", "Time", "N")
data_path = "~/Documents/PhD/Research/Scripts/R/R05/nohup002.txt"
maximals = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% 
  filter(grepl("\\|MAXIMALS\\|", line)) %>%
  slice(15:n()) %>%
  separate(line, into = fields, sep = "\\|") %>%
  mutate(Epsilon = as.numeric(Epsilon), Time = as.numeric(Time)) %>%
  group_by(Epsilon) %>% summarise(Time = mean(Time))
head(maximals, n = 24)

p = ggplot(data = maximals, aes(x = factor(Epsilon), y = Time, group = 1)) +
  geom_line() +
  geom_point() +
  ylim(c(0.7, 1.0)) +
  labs(x="Epsilon [m]", y="Average latency [s]") 
plot(p)
ggsave("LA_5K_MaximalsLatency.pdf", device = "pdf")

maximals2 = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% 
  filter(grepl("\\|MAXIMALS\\|", line)) %>%
  slice(15:n()) %>%
  separate(line, into = fields, sep = "\\|") %>%
  mutate(Epsilon = as.numeric(Epsilon), Time = as.numeric(Time)) %>%
  group_by(Epsilon) %>% summarise(tps = 300/sum(Time))
head(maximals, n = 24)

p = ggplot(data = maximals2, aes(x = factor(Epsilon), y = tps, group = 1)) +
  geom_line() +
  geom_point() +
  labs(x="Epsilon [m]", y="Throughput [tps]") 
plot(p)
ggsave("LA_5K_MaximalsThroughput.pdf", device = "pdf")

```

```{r echo=F}
fields = c("Timestamp", "Tag", "appId", "Cores", "Executors", "Epsilon", "Mu", "Partitions", "Time", "N")
data_path = "~/Documents/PhD/Research/Scripts/R/R05/nohup002.txt"
joins = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% 
  filter(grepl("\\|JOIN\\|", line)) %>%
  slice(15:n()) %>%
  separate(line, into = fields, sep = "\\|") %>%
  mutate(Epsilon = as.numeric(Epsilon), Time = as.numeric(Time)) %>%
  group_by(Epsilon) %>% summarise(Time = mean(Time))
head(joins, n = 24)

p = ggplot(data = joins, aes(x = factor(Epsilon), y = Time, group = 1)) +
  geom_line() +
  geom_point() +
  labs(x="Epsilon [m]", y="Average latency [s]") 
plot(p)
ggsave("LA_5K_JoinLatency.pdf", device = "pdf")

maximals2 = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% 
  filter(grepl("\\|JOIN\\|", line)) %>%
  slice(15:n()) %>%
  separate(line, into = fields, sep = "\\|") %>%
  mutate(Epsilon = as.numeric(Epsilon), Time = as.numeric(Time)) %>%
  group_by(Epsilon) %>% summarise(tps = 300/sum(Time))
head(maximals, n = 24)

p = ggplot(data = maximals2, aes(x = factor(Epsilon), y = tps, group = 1)) +
  geom_line() +
  geom_point() +
  labs(x="Epsilon [m]", y="Throughput [tps]") 
plot(p)
ggsave("LA_5K_JoinThroughput.pdf", device = "pdf")

```