#!/bin/bash

JAR="$HOME/Research/Scripts/Scala/GraphViewer/target/scala-2.11/graphviewer_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="${LIBSPATH}/jgrapht-core-1.4.0.jar:${LIBSPATH}/geospark-1.2.0.jar"
CLASS="edu.ucr.dblab.TestPBK"

scala -cp $LIBS:$JAR $CLASS 
