#!/bin/bash

THE_INPUT=$1
THE_EPSILON=$2
THE_MU=$3

JARS_PATH=$HOME/Spark/2.4/jars

JARS=${JARS_PATH}/geospark-1.3.1.jar
JARS=${JARS},${JARS_PATH}/scallop_2.11-4.0.1.jar
JARS=${JARS},${JARS_PATH}/archery_2.11-0.4.0.jar
JARS=${JARS},${JARS_PATH}/slf4j-api-1.7.25.jar

MASTER=local[1]

LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties
CLASS=edu.ucr.dblab.pflock.BFE
JAR=$HOME/Research/Scripts/Scala/Cliques/target/scala-2.11/cliques_2.11-0.1.jar

PARAMS=(
    --files $LOG_FILE \
    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
    --jars $JARS \
    --master $MASTER --deploy-mode client \
    --class $CLASS $JAR
    --input $THE_INPUT --epsilon $THE_EPSILON --mu $THE_MU --debug
)

echo "spark-submit ${PARAMS[@]}"
spark-submit ${PARAMS[@]}
