#!/bin/bash

N=$1

VS=( "BFE_CMBC")
ES=( 18 20 )
MS=( 3 )
#ES=( 5 )
#MS=( 3 )

for n in `seq 1 $N`
do
    for m in "${MS[@]}"
    do
	for e in "${ES[@]}"
	do
	    for v in "${VS[@]}"
	    do
		echo "./bfe /home/acald013/Research/Datasets/dense2.tsv $e $m 1 $v"
		./bfe /home/acald013/Research/Datasets/dense2.tsv $e $m 1 $v
	    done
	done
    done
done

