#!/bin/bash

N=$1

ES=( 10 12 14 16 18 20 )
MS=( 3 )
#ES=( 5 )
#MS=( 3 )

for n in `seq 1 $N`
do
    for e in "${ES[@]}"
    do
	for m in "${MS[@]}"
	do
	    echo "./bfe2 /home/acald013/Research/Datasets/P10K_W1K_H1K.tsv $e $m 1"
	    ./bfe2 /home/acald013/Research/Datasets/P10K_W1K_H1K.tsv $e $m 1
	done
    done
done

