#!/bin/bash

N=$1

#ES=( 5 6 7 8 9 10 )
#MS=( 3 4 5 6 7 8 )
ES=( 5 6 )
MS=( 3 4 )

for n in `seq 1 $N`
do
    for e in "${ES[@]}"
    do
	for m in "${MS[@]}"
	do
	    echo "./bfe /home/acald013/Research/Datasets/ $e $m 1"
	done
    done
done

