#!/bin/bash

DATASET=$1
VARIANT=$2

ES=( 5 6 7 8 9 10 15 )
MS=( 3 )
#ES=( 5 )
#MS=( 3 )

for m in "${MS[@]}"
do
    for e in "${ES[@]}"
    do
	echo "./bfe $DATASET $e $m 1 $VARIANT --debug"
	./bfe $DATASET $e $m 1 $VARIANT --debug
    done
done

