#!/bin/bash

TS=( 318 319 320 )
CS=( 500 1000 1500 2000 )
ES=( 4 6 8 10 )

for t in "${TS[@]}"
do
    for c in "${CS[@]}"
    do
	for e in "${ES[@]}"
	do
	    echo "./cell_explorer /home/acald013/Datasets/LA/LA_50K_T${t}.tsv $c $e \"T${t}_C${c}\""
	    ./cell_explorer /home/acald013/Datasets/LA/LA_50K_T${t}.tsv $c $e "T${t}_C${c}"
	done
    done
done

