#!/bin/bash

THE_INPUT=$1
THE_CAPACITY=$2
THE_TAG=$3

JARS_PATH=$HOME/Spark/2.4/jars

JARS=${JARS_PATH}/geospark-1.3.1.jar
JARS=${JARS},${JARS_PATH}/scallop_2.11-4.0.1.jar
JARS=${JARS},${JARS_PATH}/slf4j-api-1.7.25.jar

MASTER=local[10]
EXECUTORS=12
CORES=9

LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties
CLASS=edu.ucr.dblab.pflock.CellExplorer
JAR=$HOME/Research/Scripts/Scala/Cliques/target/scala-2.11/cliques_2.11-0.1.jar

PARAMS=(
    --files $LOG_FILE \
    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
    --jars $JARS \
    --master $MASTER --deploy-mode client \
    --num-executors $EXECUTORS --executor-cores $CORES \
    --class $CLASS $JAR
    --input $THE_INPUT --capacity $THE_CAPACITY --tag $THE_TAG
)

echo "spark-submit ${PARAMS[@]}"
spark-submit ${PARAMS[@]}
