#!/bin/bash

INPUT=$1
EPSILON=$2
MU=$3
DELTA=$4
DEBUG=$5
MASTER=$6

WAIT="0s"
EXECUTORS=12
CORES=9
DMEMORY=35g
EMEMORY=20g
MAX_RESULT_SIZE="4G"
KRYO_BUFFER_MAX="256m"

JARS_PATH=$HOME/Spark/2.4/jars

JARS=${JARS_PATH}/geospark-1.3.1.jar
JARS=${JARS},${JARS_PATH}/scallop_2.11-4.0.1.jar
JARS=${JARS},${JARS_PATH}/slf4j-api-1.7.25.jar
JARS=${JARS},${JARS_PATH}/archery_2.11-0.6.0.jar
JARS=${JARS},${JARS_PATH}/jgrapht-core-1.4.0.jar
JARS=${JARS},${JARS_PATH}/commons-geometry-core-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-geometry-enclosing-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-geometry-euclidean-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-numbers-fraction-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-numbers-core-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-numbers-arrays-1.0-beta1.jar

LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties
CLASS=edu.ucr.dblab.pflock.GridPartitioner
JAR=$HOME/Research/Scripts/Scala/Cliques/target/scala-2.11/cliques_2.11-0.1.jar

PARAMS=(
    --files $LOG_FILE \
	    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
	    --conf spark.driver.maxResultSize=$MAX_RESULT_SIZE \
	    --conf spark.kryoserializer.buffer.max=$KRYO_BUFFER_MAX \
	    --conf spark.locality.wait=$WAIT \
	    --jars $JARS \
	    --master $MASTER --deploy-mode client \
	    --num-executors $EXECUTORS --executor-cores $CORES \
	    --executor-memory $EMEMORY --driver-memory $DMEMORY \
	    --class $CLASS $JAR \
	    --input $INPUT $DEBUG --epsilon $EPSILON --mu $MU 
)

echo "spark-submit ${PARAMS[@]}"
spark-submit ${PARAMS[@]}
