#!/bin/bash

N=$1

ES=( 2 5 10 15 20 )
CS=( 100 250 500 750 1000 )
#ES=( 5 )
#MS=( 3 )

for n in `seq 1 $N`
do
    for e in "${ES[@]}"
    do
	for c in "${CS[@]}"
	do
	    echo "./mf Datasets/LA_50K_T320.tsv $e 3 1 $c 1 --debug yarn"
	    ./mf Datasets/LA_50K_T320.tsv $e 3 1 $c 1 --debug yarn
	done
    done
done
