```{r, echo=FALSE, include=FALSE, message=FALSE}
  arr = str_split(afile, "_")
  time_instant = str_sub(arr[[1]][2],2,-1)
  capacity     = str_sub(arr[[1]][3],2,-1)
  leafs        = str_split(str_sub(arr[[1]][4],2,-1), "\\.")[[1]][1]
  
  data = read_tsv(paste0("data2/",afile), col_names = c("wkt", "cid", "n"))
```

```{r,echo=FALSE, results='asis'} 
cat(paste0("\nTime instant   : ",  time_instant, " (capacity=", capacity,", leafs=", leafs,").\\"))
```
------------------------------------

```{r,echo=FALSE, results='asis'}
cat("\nMinimum value  : ", min(na.omit(data$n)), "\\")
cat("\nPercentile 1%  : ",  quantile(na.omit(data$n),probs = seq(0, 1, 0.01))[2], "\\")
cat("\nPercentile 99% : ", quantile(na.omit(data$n),probs = seq(0, 1, 0.01))[100], "\\")
cat("\nMaximum value  : ", max(na.omit(data$n)), "\n")
```

```{r, echo=FALSE, results='asis'}
warn_extreme_values=3
d1  = quantile(na.omit(data$n),probs = seq(0, 1, 0.01))[2]   > warn_extreme_values * quantile(na.omit(data$n),probs = seq(0, 1, 0.01))[1]
d99 = quantile(na.omit(data$n),probs = seq(0, 1, 0.01))[101] > warn_extreme_values * quantile(na.omit(data$n),probs = seq(0, 1, 0.01))[100]
if(d1){cat('Warning : Suspect extreme values in left tail \\')}
if(d99){cat('Warning : Suspect extreme values in right tail \\')}
```

```{r, echo=FALSE, message=FALSE, fig.width=4, fig.height=3, fig.align='center'}
  p = ggplot(data, aes(x = n)) + geom_histogram(color="black", fill="white")
  suppressWarnings(print(p))
```

\pagebreak