---
title: "R Notebook"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r include=FALSE}
library(plotly)
source("/home/and/Documents/PhD/Research/Scripts/R/R13/tasksMetrics.R")

nohup = "/home/and/Documents/PhD/Research/Scripts/R/R14/nohup.tsv"
appsE1_1 = getCustomStages2(nohup, "004")
appsE1_2 = getCustomStages2(nohup, "006")
appsE1_4 = getCustomStages2(nohup, "010")
appsE1_5 = getCustomStages2(nohup, "012")
stagesE1 = rbind(appsE1_1,appsE1_2, appsE1_4, appsE1_5)
appsE3_1 = getCustomStages2(nohup, "005")
appsE3_2 = getCustomStages2(nohup, "007")
appsE3_3 = getCustomStages2(nohup, "009")
appsE3_4 = getCustomStages2(nohup, "011")
stagesE3 = rbind(appsE3_1,appsE3_2,appsE3_3, appsE3_4)
```


```{r}
stages = rbind(stagesE1, stagesE3) %>% select(Interval, Stage, Executors, Duration) %>%
  mutate(Stage = paste(str_pad(Interval,2,"left"), Stage)) %>%
  select(Stage, Executors, Duration) %>%
  group_by(Stage, Executors) %>% summarise(Duration = mean(Duration))

head(stages)

```

```{r}
p = ggplot(data = stages, aes(x = Stage, y = Duration, fill = Executors)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stages", y="Duration(s)")
plot(p)
```


```{r}
stages = customExecutionTime(nohup)

data = stages %>% select(Executors, Epsilon, Duration) %>%
  group_by(Executors, Epsilon) %>% summarise(Duration = mean(Duration))
head(data)
```

```{r echo=FALSE}
p = ggplot(data = data, aes(x = Epsilon, y = Duration, fill = Executors)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Epsilon(mts)", y="Duration(s)")
plot(p)
```