---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r}
library(tidyverse)
library(ggplot2)
library(plotly)
```

```{r}
source("/home/and/Documents/PhD/Research/Scripts/R/R13/tasksMetrics.R")

nohup = "/home/and/Documents/PhD/Research/Scripts/R/R14/nohupAWS012.txt"
cores = 6
epsilon = 90.0
stages1 = bind_rows(getAppIDs(nohup, cores, executors = 3, epsilon) %>% map(getStages))
stages2 = bind_rows(getAppIDs(nohup, cores, executors = 6, epsilon) %>% map(getStages))
stages3 = bind_rows(getAppIDs(nohup, cores, executors = 9, epsilon) %>% map(getStages))

stages = rbind(stages1, stages2, stages3) %>% select(StageId, Stage, Executors, Duration) %>%
  group_by(StageId, Stage, Executors) %>% summarise(Duration = mean(Duration))

data = stages %>% ungroup() %>% mutate(Stage = paste(str_pad(StageId, 5, "left"), Stage))
p = ggplot(data = data, aes(x = Stage, y = Duration, fill = Executors)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stages", y="Duration(s)")
ggplotly(p)
```

```{r}
data = stages %>% ungroup() %>% 
  select(Executors, Duration) %>% group_by(Executors) %>% summarise(Duration = sum(Duration))
head(data)
data$Epsilon = as.factor(epsilon)
p = ggplot(data = data, aes(x = Epsilon, y = Duration, fill = Executors)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Epsilon", y="Duration(s)")
plot(p)
```

```{r}
stagesByDiff = stages %>% group_by(StageId, Stage) %>% 
  summarise(min=min(Duration), max=max(Duration), mean=mean(Duration), sd=sd(Duration)) %>%
  mutate(diff = max - min) %>%
  arrange(desc(diff))
stagesByDiff
```

```{r}
source("/home/and/Documents/PhD/Research/Scripts/R/R13/tasksMetrics.R")
tasks1 = getTasksStats(nohup, cores, executors = 3, epsilon)
tasks2 = getTasksStats(nohup, cores, executors = 6, epsilon)
tasks3 = getTasksStats(nohup, cores, executors = 9, epsilon)
tasks = rbind(tasks1, tasks2, tasks3) 
tasks
```

```{r}
topN = 10
stagesByHost = stagesByDiff[1:topN,] %>% select(StageId) %>% inner_join(tasks, by = c("StageId")) 
stagesByHost
```

```{r}
tasksByHost = stagesByHost %>% group_by(Executors, StageId, Stage) %>% 
  summarise(minN=min(N), maxN=max(N), sdN=sd(N), 
            minD=min(Duration), maxD=max(Duration), sdD=sd(Duration)) %>%
  mutate(diffN = maxN - minN, diffD = maxD - minD) %>%
  select(Executors, StageId, Stage, sdN, diffN, sdD, diffD) %>%
  arrange(StageId)
 
tasksByHost
```

```{r}
data = tasksByHost %>% mutate(Stage = paste(str_pad(StageId,pad = "0", width = 5), str_trim(Stage, side = "both"))) %>%
  select(Executors,Stage, diffN, diffD)

p = ggplot(data = data, aes(x = Stage, y = diffN, fill = Executors)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stage", y="N") 
plot(p)

```

```{r}
p = ggplot(data = data %>% filter(Executors == 3), aes(x = Stage, y = Duration, fill = Host)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stage", y="Duration") 
plot(p)

p = ggplot(data = data %>% filter(Executors == 6), aes(x = Stage, y = Duration, fill = Host)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stage", y="Time") 
plot(p)
p = ggplot(data = data %>% filter(Executors == 9), aes(x = Stage, y = Duration, fill = Host)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stage", y="Time") 
plot(p)
```

