---
title: "FlockFinder Analysis"
author: "Andres Calderon"
date: '`r Sys.Date()`'
output:
  pdf_document: default
  html_document: 
    theme: paper
params:
  phd_path:
    value: "Y3Q1/Scripts/Scaleup/"
  filename:
    value: "Berlin_14-1112-111214-11121415_Reverse"
  extension:
    value: "out"
---

<!--- Reading data... --->
Default values: \(\varepsilon\)=20.0, \(\mu\)=4 and \(\delta\)=4

```{r ScaleupSetup, include=FALSE}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, data.table, foreach, sqldf, tidyr, stringr, dplyr)
source('DataFromLogs.R')

dataFile = '/home/and/Documents/PhD/Research/Experiments/FlockFinder_v1.0/nohup.out'

data = getDataByMethod(dataFile)
```

## Plotting \(\varepsilon\)

```{r EpsilonPlot, echo=FALSE, fig.width=10.5, fig.height=7.5, fig.align='center'}
dataEpsilon = data[data$Mu == '3' & data$Delta == '3', ]  
temp_title = paste("(radius of disk in mts) in Berlin dataset.")
title = substitute(paste("Execution time by ", epsilon) ~ temp_title, list(temp_title = temp_title))
g = ggplot(data=dataEpsilon, aes(x=factor(Epsilon), y=Time, fill=Method)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75),width = 0.75) +
  labs(title=title, y="Time(s)", x=expression(paste(epsilon,"(mts)")))
plot(g)
```

## Plotting \(\mu\)

```{r MuPlot, echo=FALSE, fig.width=10.5, fig.height=7.5, fig.align='center'}
dataMu = data[data$Epsilon == '20.0' & data$Delta == '4', ]  
temp_title = paste("(number of moving objects) in Berlin dataset.")
title = substitute(paste("Execution time by ", mu) ~ temp_title, list(temp_title = temp_title))
g = ggplot(data=dataMu, aes(x=factor(Mu), y=Time, fill=Method)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75),width = 0.75) +
  labs(title=title, y="Time(s)", x=expression(paste(mu," (# of objects)")))
plot(g)
```

## Plotting \(\delta\)

```{r DeltaPlot, echo=FALSE, fig.width=10.5, fig.height=7.5, fig.align='center'}
dataDelta = data[data$Epsilon == '10.0' & data$Mu == '4', ]  
temp_title = paste("(consecutive timestamps) in Berlin dataset.")
title = substitute(paste("Execution time by ", delta) ~ temp_title, list(temp_title = temp_title))
g = ggplot(data=dataDelta, aes(x=factor(Delta), y=Time, fill=Method)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75),width = 0.75) +
  labs(title=title, y="Time(s)", x=expression(paste(delta," (# consecutive timestamps)")))
plot(g)
```
