#!/bin/bash

INPUT=$1
EPSILON=$2
MU=$3

JAR="$HOME/Research/Scripts/Scala/FF/target/scala-2.11/ff_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="${LIBSPATH}/jgrapht-core-1.4.0.jar:$LIBSPATH/geospark-1.2.0.jar:$LIBSPATH/scallop_2.11-4.0.1.jar:${LIBSPATH}/commons-numbers-fraction-1.0-beta1.jar:${LIBSPATH}/commons-numbers-core-1.0-beta1.jar:${LIBSPATH}/commons-numbers-arrays-1.0-beta1.jar:${LIBSPATH}/commons-geometry-core-1.0-beta1.jar:${LIBSPATH}/commons-geometry-enclosing-1.0-beta1.jar:${LIBSPATH}/commons-geometry-euclidean-1.0-beta1.jar"

CLASS="edu.ucr.dblab.pflock.FF_prime"

export JAVA_OPTS="-Xmx2g" 
scala -cp "$LIBS:$JAR" $CLASS --input $INPUT --epsilon $EPSILON --mu $MU --tolerance 1e-3 --debug
