#!/bin/bash

N=$1
BEGIN=$2
END=$3

TIME=$((END - BEGIN))
PERIOD=$(bc <<< "scale=5;$TIME/$N")

echo "The period was set to $PERIOD"

## Pedestrian
echo "Pedestrians..."
python "$SUMO_HOME/tools/randomTrips.py" \
       --pedestrians \
       --net-file dense.net.xml.gz --begin $BEGIN --end $END --period $PERIOD \
       --output-trip-file dense.pedestrian.trips.xml --route-file dense.pedestrian.rou.xml \
       --validate --remove-loops \
       --vehicle-class pedestrian --prefix ped \
       --random --seed 42 --duarouter-routing-threads 3 \
       --verbose \
       --via-edge-types highway.motorway,highway.motorway_link,highway.trunk_link,highway.primary_link,highway.secondary_link,highway.tertiary_link 
