#!/bin/bash

N=$1

VS=( "BFE")
#ES=( 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 )
MS=( 3 4 5 6 7 8 9 10 11 12 13 )
ES=( 20 )
#MS=( 3 )

for n in `seq 1 $N`
do
    for m in "${MS[@]}"
    do
	for e in "${ES[@]}"
	do
	    for v in "${VS[@]}"
	    do
		#./bfe /home/acald013/Research/Datasets/LA_50K_T320.tsv $e 3 1 BFE
		echo "./mf --input PFlock/LA/LA_50K_T320 --epsilon $e --mu $m --delta 1 --capacity 250 --master yarn --tester"
		./mf --input PFlock/LA/LA_50K_T320 --epsilon $e --mu $m --delta 1 --capacity 250 --master yarn --tester
	    done
	done
    done
done

