#!/bin/bash

TS=( 320 )
CS=( 100 200 400 600 800 1000 )
ES=( 12 14 16 18 20 )

for t in "${TS[@]}"
do
    for c in "${CS[@]}"
    do
	for e in "${ES[@]}"
	do
	    echo "./cell_explorer /home/acald013/Datasets/LA/LA_50K_T${t}.tsv $c $e \"T${t}_C${c}\""
	    ./cell_explorer /home/acald013/Datasets/LA/LA_50K_T${t}.tsv $c $e "T${t}_C${c}"
	done
    done
done

