#!/bin/bash

PARGS=()
while [[ "$1" != "" ]]; do
    case $1 in
	-x|--executors)
	    shift
	    EXECUTORS="$1"
	    ;;	
	-w|--wait)
	    shift
	    WAIT="$1"
	    ;;
	*)
	    PARGS+=("$1") # save positional arg
	    ;;
    esac
    shift
done
set -- "${PARGS[@]}" # restore positional parameters
if [ -v EXECUTORS ]; then echo "EXECUTORS  = $EXECUTORS"; else EXECUTORS=12;  echo "EXECUTORS  = $EXECUTORS"; fi
if [ -v WAIT ];      then echo "WAIT       = $WAIT";      else WAIT="0s";     echo "WAIT       = $WAIT";      fi

CORES=9
DMEMORY=35g
EMEMORY=20g
MAX_RESULT_SIZE="4G"
KRYO_BUFFER_MAX="256m"

JARS_PATH=$HOME/Spark/2.4/jars

JARS=${JARS_PATH}/jts-core-1.19.0.jar
JARS=${JARS},${JARS_PATH}/scallop_2.11-4.0.1.jar
JARS=${JARS},${JARS_PATH}/slf4j-api-1.7.25.jar
JARS=${JARS},${JARS_PATH}/archery_2.11-0.6.0.jar
JARS=${JARS},${JARS_PATH}/jgrapht-core-1.4.0.jar
JARS=${JARS},${JARS_PATH}/commons-geometry-core-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-geometry-enclosing-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-geometry-euclidean-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-numbers-fraction-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-numbers-core-1.0-beta1.jar
JARS=${JARS},${JARS_PATH}/commons-numbers-arrays-1.0-beta1.jar

LOG_FILE=$HOME/Spark/2.4/conf/log4j.properties
CLASS=edu.ucr.dblab.pflock.MF
JAR=$HOME/Research/Scripts/Scala/PFlock/target/scala-2.11/pflock_2.11-0.1.0.jar

PARAMS=(
    --files $LOG_FILE \
	    --conf spark.driver.extraJavaOptions=-Dlog4j.configuration=file:$LOG_FILE \
	    --conf spark.driver.maxResultSize=$MAX_RESULT_SIZE \
	    --conf spark.kryoserializer.buffer.max=$KRYO_BUFFER_MAX \
	    --conf spark.locality.wait=$WAIT \
	    --jars $JARS \
	    --deploy-mode client \
	    --num-executors $EXECUTORS --executor-cores $CORES \
	    --executor-memory $EMEMORY --driver-memory $DMEMORY \
	    --class $CLASS $JAR 
)

echo "spark-submit ${PARAMS[@]} ${PARGS[@]}"
spark-submit ${PARAMS[@]} ${PARGS[@]}
