#!/bin/bash

./mf --input PFlock/LA/LA_50K_T320 --epsilon 20 --mu 3 --delta 1 --capacity 100 --fraction 1 --density 0 --master yarn --debug

N=$1

ES=( 20 ) # epsilon
MS=( 3 ) # mu
CS=( 100 ) # capacity
DS=( 1000 2000 3000 4000 5000 6000 7000 8000 ) # density

for n in `seq 1 $N`
do
    for d in "${DS[@]}"
    do
	for e in "${ES[@]}"
	do
	    for m in "${MS[@]}"
	    do
		for c in "${CS[@]}"
		do
		    echo "$n ./mf --input PFlock/LA/LA_50K_T320 --epsilon $e --mu $m --delta 1 --capacity $c --fraction 1 --density $d --master yarn"
		    ./mf --input PFlock/LA/LA_50K_T320 --epsilon $e --mu $m --delta 1 --capacity $c --fraction 1 --density $d --master yarn 
		done
	    done
	done
    done
done
