#!/bin/bash


N=$1
#DATASET=PFlock/LA/LA_50K_T320
DATASET=Datasets/dense

ES=( 20 ) # epsilon
MS=( 3 ) # mu
CS=( 250 ) # capacity
DS=( 0 8000 ) # density

for n in `seq 1 $N`
do
    for d in "${DS[@]}"
    do
	for e in "${ES[@]}"
	do
	    for m in "${MS[@]}"
	    do
		for c in "${CS[@]}"
		do
		    echo "$n ./mf --input $DATASET --epsilon $e --mu $m --delta 1 --capacity $c --fraction 1 --density $d --master yarn"
		    ./mf --input $DATASET --epsilon $e --mu $m --delta 1 --capacity $c --fraction 1 --density $d --master yarn
		done
	    done
	done
    done
done
