#!/bin/bash


N=$1

ES=( 14 18 ) # epsilon
MS=( 3 ) # mu

for n in `seq 1 $N`
do
	for e in "${ES[@]}"
	do
		for m in "${MS[@]}"
		do
			echo "Running..."
			bash/checker_scala --dataset ~/Research/Datasets/dense_recode.tsv --epsilon $e --mu $m --tester
		done
	done
done
