#!/bin/bash 

PARAMS=(
 --files  /home/acald013/Spark/2.4/conf/log4j.properties   \
 --conf   spark.driver.extraJavaOptions=-Dlog4j.configuration=file:/home/acald013/Spark/2.4/conf/log4j.properties   \
 --jars   /home/acald013/.cache/coursier/v1/https/repo1.maven.org/maven2/org/locationtech/jts/jts-core/1.19.0/jts-core-1.19.0.jar,/home/acald013/.cache/coursier/v1/https/repo1.maven.org/maven2/org/rogach/scallop_2.11/4.0.1/scallop_2.11-4.0.1.jar,/home/acald013/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar,/home/acald013/.cache/coursier/v1/https/repo1.maven.org/maven2/tech/tablesaw/tablesaw-core/0.43.1/tablesaw-core-0.43.1.jar,/home/acald013/.cache/coursier/v1/https/repo1.maven.org/maven2/tech/tablesaw/tablesaw-jsplot/0.43.1/tablesaw-jsplot-0.43.1.jar,/home/acald013/Research/Scripts/Scala/Tester3D/lib/spark3d_2.11-0.3.1.jar,/home/acald013/Research/Scripts/Scala/Tester3D/lib/jhealpix.jar,/home/acald013/Research/Scripts/Scala/Tester3D/lib/plotly-assembly-0.3.0-SNAPSHOT.jar  \
 --master local[*]  \
 --class  edu.ucr.dblab.pflock.LATrajsAnalyzer  
)

spark-submit ${PARAMS[@]} /home/acald013/Research/Scripts/Scala/Tester3D/target/scala-2.11/tester3d_2.11-0.1.0.jar $* 
