---
title: "LA Dataset"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

## Reviewing execution time and load from time instance 15 to 20
* Epsion = 25m
* Mu = 5
```{r include=F}
library(tidyverse)
library(knitr)
library(kableExtra)
nExperiments = 180

plotTimeInstant <- function(data, instant){
  data0 = data %>% filter(Instant == instant) %>% select(Stage, CellSize, Input, Output, Time)
  data0[data0$Stage == "A.Partitioning points", "Input"] = data0[data0$Stage == "A.Partitioning points", "Output"]
  
  p = ggplot(data = data0, aes(x = Stage, y = Time, fill = factor(CellSize))) +
    geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0 )) +
    labs(x="Stage", y="Time [s]", title="Stage execution time by cell size", fill="Cell Size") 
  plot(p)
  
  data1 = data0 %>% select(Stage, CellSize, Input, Output) %>% gather(Params, Records, -Stage, -CellSize)
  g = ggplot(data = data1, aes(x = Stage, y = Records, fill = factor(Params))) +
    geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
    theme(axis.text.x = element_text(angle = 90, hjust = 0, vjust = 0)) +
    labs(x="Stage", y="Number of records [n]", title="Input and output at each stage by cell size", fill="") +
    facet_grid(cols = vars(CellSize))
  plot(g)
  return(data0)
}
```

```{r echo=F}
fields3 = c("Timestamp", "Tag", "appId", "Executors", "Cores", "Status", "Duration", "Stage", "Time", "Load", "Interval")
data_path = "~/Documents/PhD/Research/Scripts/R/R19/Plots/nohupMF2.txt"
stages = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% filter(grepl("\\|MF\\|", line)) %>%
  filter(grepl("END", line)) %>% separate(line, into = fields3, sep = "\\|") %>%
  filter(grepl("[A-F]\\.", Stage)) %>%
  mutate(Time = as.numeric(Time), Load = as.numeric(Load)) %>%
  select(Stage, Time, Load) %>% mutate(id = rep(1:nExperiments, each = 6))

submit = enframe(read_lines(data_path), name = "n", value = "line") %>% select(line) %>% 
  filter(grepl("spark-submit", line)) %>% separate(line, into=paste0("A", 1:16), sep = "--") %>% 
  mutate(A11 = str_trim(A11), A12 = str_trim(A12)) %>%
  separate(A11, c(NA,"Instant"), sep = " ") %>% separate(A12, c(NA,"CellSize"), sep = " ") %>%
  select(Instant, CellSize) %>% mutate(Instant = as.numeric(Instant), CellSize = as.numeric(CellSize)) %>% 
  mutate(id = 1:nExperiments)
stage_names = tibble(StageId = c("A","B","C","D","E","F"), StageName = c("Partitioning points", "Finding pairs", "Computing centers", "Finding disks", "Partitioning disks", "Maximal disks"))
data = stages %>% inner_join(submit, by = "id") %>%
  group_by(Instant, CellSize, Stage) %>% summarise(Time = mean(Time), Output = min(Load)) %>%
  ungroup() %>% separate(Stage, c("StageId", NA), sep = "\\.") %>% inner_join(stage_names, by = "StageId") %>%
  mutate(Stage = paste0(StageId,".",StageName)) %>% select(Instant, CellSize, Stage, Time, Output)
head(data, n=nExperiments)
data$Input = c(0, data$Output[1:(length(data$Output) - 1)])
```

### At time instant 15
```{r echo=F, fig.width=10}
data0 = plotTimeInstant(data, 15)
head(data0, 36)
```
### At time instant 16
```{r echo=F, fig.width=10}
data0 = plotTimeInstant(data, 16)
head(data0, 36)
```
### At time instant 17
```{r echo=F, fig.width=10}
data0 = plotTimeInstant(data, 17)
head(data0, 36)
```
### At time instant 18
```{r echo=F, fig.width=10}
data0 = plotTimeInstant(data, 18)
head(data0, 36)
```
### At time instant 19
```{r echo=F, fig.width=10}
data0 = plotTimeInstant(data, 19)
head(data0, 36)
```
### At time instant 20
```{r echo=F, fig.width=10}
data0 = plotTimeInstant(data, 20)
head(data0, 36)
```
