#!/bin/bash

JAR="$HOME/Research/Scripts/Scala/FF/target/scala-2.11/ff_2.11-0.1.jar"
LIBSPATH="$HOME/Spark/2.4/jars"
LIBS="${LIBSPATH}/jgrapht-core-1.4.0.jar:$LIBSPATH/jts-core-1.18.0.jar:${LIBSPATH}/commons-math3-3.6.1.jar"
CLASS="edu.ucr.dblab.pflock.pbk.PBK_Tester"

scala -cp $LIBS:$JAR $CLASS $1 $2
