---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r include=FALSE}
library(plotly)
source("/home/and/Documents/PhD/Research/Scripts/R/R13/tasksMetrics.R")

nohup = "/home/and/Documents/PhD/Research/Scripts/R/R14/nohupAWS8.txt"
appsE1_1 = getCustomStages2(nohup, "013")
appsE1_2 = getCustomStages2(nohup, "016")
appsE1_3 = getCustomStages2(nohup, "019")
#appsE1_4 = getCustomStages2(nohup, "022")
#appsE1_5 = getCustomStages2(nohup, "024")
stagesE1 = rbind(appsE1_1, appsE1_2, appsE1_3)#, appsE1_4, appsE1_5)
appsE2_1 = getCustomStages2(nohup, "014")
appsE2_2 = getCustomStages2(nohup, "017")
appsE2_3 = getCustomStages2(nohup, "020")
#appsE2_4 = getCustomStages2(nohup, "023")
#appsE2_5 = getCustomStages2(nohup, "025")
stagesE2 = rbind(appsE2_1, appsE2_2, appsE2_3)#, appsE2_4, appsE2_5)
appsE3_1 = getCustomStages2(nohup, "015")
appsE3_2 = getCustomStages2(nohup, "018")
appsE3_3 = getCustomStages2(nohup, "021")
#appsE3_4 = getCustomStages2(nohup, "024")
#appsE3_5 = getCustomStages2(nohup, "026")
stagesE3 = rbind(appsE3_1, appsE3_2, appsE3_3)#, appsE3_4, appsE3_5)
levels = c("3","6","9")
```


```{r}
stages = rbind(stagesE1, stagesE2, stagesE3) %>% select(Interval, Stage, Executors, Duration) %>%
  mutate(Stage = paste(str_pad(Interval,2,"left"), Stage)) %>%
  select(Stage, Executors, Duration) %>%
  group_by(Stage, Executors) %>% summarise(Duration = mean(Duration))
stages$Executors = factor(stages$Executors, levels = levels)
head(stages)

```

```{r}

p = ggplot(data = stages, aes(x = Stage, y = Duration, fill = Executors)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Stages", y="Duration(s)")
plot(p)
```


```{r}
stages = customExecutionTime(nohup)

data = stages %>% select(Executors, Epsilon, Duration) %>%
  group_by(Executors, Epsilon) %>% summarise(Duration = mean(Duration))
data$Executors = factor(data$Executors, levels = levels)
head(data)
```

```{r echo=FALSE}
p = ggplot(data = data, aes(x = Epsilon, y = Duration, fill = Executors)) +
  geom_bar(stat="identity", position=position_dodge(width = 0.75), width = 0.7) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(x="Epsilon(mts)", y="Duration(s)")
plot(p)
```